name: business_calendar
description: A new Flutter project for Business Calendar.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.5.5
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo.png
    - assets/onboard1.png
    - assets/onboard2.png
    - assets/onboard3.png
    - assets/call.png
    - assets/sms-tracking.png
