// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7l6rfZ3J8-703jE6yJv6z6-VhsSoXQHE',
    appId: '1:596943413242:web:edcfe9b7ab4ffa778b4e43',
    messagingSenderId: '596943413242',
    projectId: 'businesscalendar-c34a2',
    authDomain: 'businesscalendar-c34a2.firebaseapp.com',
    storageBucket: 'businesscalendar-c34a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2sjJz-kIwUHa1624TX2SlnRc4p_LxgD8',
    appId: '1:596943413242:android:d3b0663b9016cb448b4e43',
    messagingSenderId: '596943413242',
    projectId: 'businesscalendar-c34a2',
    storageBucket: 'businesscalendar-c34a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP88iRIZGuDPeYqMDmW9uWaU7b3K9EyJg',
    appId: '1:596943413242:ios:f2a6c66a6ca4dc188b4e43',
    messagingSenderId: '596943413242',
    projectId: 'businesscalendar-c34a2',
    storageBucket: 'businesscalendar-c34a2.firebasestorage.app',
    iosBundleId: 'com.example.businessCalendar',
  );
}
